apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    # Service port
  - port: 80
    protocol: TCP
    # Container port
    targetPort: 3000
  selector:
    app: api
  type: ClusterIP
